---
apiVersion: v1
kind: Service
metadata:
  name: "service-node-port"
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
  selector:
    app: "my-app"
