# my-app-sm.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-app
  namespace: monitoring
  labels:
    release: kps               
spec:
  namespaceSelector:
    matchNames: ["default"]   
  selector:
    matchLabels:
      app: my-app            
  endpoints:
    - port: http
      scheme: http
      path: /metrics           #
      interval: 15s
      scrapeTimeout: 10s
